### ISSUE TITLE
The spinner keeps spinning when rendering a table with the same data

### ISSUE THREAD

**Issue by greenTea2Codes** [andrewsali/shinycssloaders#10] opened 2017-12-04 20:32 UTC
Hi I am new to R and shiny.
I use the spinner like below:
in the UI block:
`withSpinner(tableOutput("freq_table"))`

in the Server block:
`
observeEvent(input$button, {
  df_log <<- update(input$dateRange[1], input$dateRange[2])
})
output$freq_table <- renderTable({
  input$button
  df_freq_table <- as.data.frame(table(df_log$user_id)) 
  colnames(df_df_freq_table) <- c("user_id", "count")
  df_freq_table <- df_freq_table[order(-df_freq_table$count, df_freq_table$user_id),]
  df_freq_table
})`

When the date range changes, the table is rendered. But if the date range is the same, the spinner just keep spinning. 
The table renders if I remove the spinner.
Could someone tell me why the spinner keeps spinning if the data is the same? Is there a way to tell the spinner that the table is updated even though the data set is the same?
Thank you

**Comment by andrewsali** [comment] 2017-12-05 07:35
If you are not using the latest github version (updated a few days ago),
could you try to see if installing that resolves the issue?

Otherwise we will need a complete reproducible example to be able to dig
into what might be the exact problem in this case.

**Comment by greenTea2Codes** [comment] 2017-12-05 08:50
Hi, I have been using v.0.2.0 from CRAN.
I tried `devtools::install_github('andrewsali/shinycssloaders')` in the R studio console
but when I did `packageVersion("shinycssloaders")` 
I still got v. 0.2.0.
Could you advise me how to get your latest version?
Kind regards

**Comment by andrewsali** [comment] 2017-12-05 09:26
That's the right way, just restart your R session and load the library
again and it should be the new one.

You can check the exact version using devtools::session_info()

**Comment by greenTea2Codes** [comment] 2017-12-05 10:46
Hi, 
After I ran my app in the R studio and did devtools::session_info() I got
chinycssloaders *0.2.0 2017-12-05 Github (andrewsali/shinycssloaders@8779ff0)
Does it mean I am still using v.0.2.0? Should I re-install or update the package?

**Comment by andrewsali** [comment] 2017-12-05 11:07
That looks correct, it's the latest version - do you still experience the
issue? Also, before (the first time you experienced the problem) you were
using the CRAN version?

If the answer to both questions is yes, then we will need a complete
(runnable) reproducible example to be able to investigate.

**Comment by greenTea2Codes** [comment] 2017-12-05 12:38
Yes to both of your questions. I am afraid that I cannot post the complete scripts here - one way I could do is to simplify the codes and reproduce the issue in a new project. I wish I would have time later for further study.

At the moment, I removed the spinners from tableOutputs and the tables render as expected even if the dataset is the same. It works fine for the plotOutputs though, which puzzles me. I will post more if I learn more from the issue. 

Thank you for your replies.

**Comment by andrewsali** [comment] 2017-12-06 13:25
If you could contribute a reproducible issue, that would be highly appreciated. I will keep the issue open for 2 weeks, if you can provide an example by then that would be great. Otherwise after I will close the issue due to lack of reproducibility.

**Comment by andrewsali** [comment] 2017-12-30 18:26
Closing as there is no reproducible example.

**Comment by alexturcan** [comment] 2018-02-20 16:08
I've been experiencing the same issue. Given a table and a plot output each with a spinner, the first time around they both complete successfully, but any subsequent rendering completes only for the plot, while the table spinner persists.

Here is a reproducible example:

```R
library(shiny)
library(shinycssloaders)

ui <- fluidPage(
  actionButton("execute", "Execute"),
  withSpinner(plotOutput("plot")),
  withSpinner(tableOutput("table"))
)

server <- function(input, output) {
  
  our_data <- reactive({
    input$execute
    
    data.frame(n = seq(0,100,5))
  })
  
  output$plot <- renderPlot({
    hist(our_data()$n)
  })
  
  output$table <- renderTable({
    our_data()
  })
}

shinyApp(ui, server)
```

**Comment by andrewsali** [comment] 2018-02-20 21:09
Thanks for the reproducible example. The issue seems to be that `shiny:value` event is not triggered when the same data is received for the table, even though the client seems to be sending the data. I'll reach out to Shiny team to understand if this is really what they intended.

**Comment by alexturcan** [comment] 2018-03-06 11:13
Hi Andrew, I was wondering if there's been any progress on this issue? Thank you.

**Comment by andrewsali** [comment] 2018-03-17 19:14
Apologies for the delay, I was a bit under water. Opened an issue in the shiny github repo, it seems an issue on their end.

**Comment by AkshataSalian** [comment] 2018-04-12 06:39
Hi Andrew, I am also facing this issue. Any update so far on this?

**Comment by andrewsali** [comment] 2018-04-12 08:47
I have proposed a fix for Shiny, it will probably be integrated soon into their master branch. Until that happens, you can install my fix that should resolve the problem via:

```
devtools::install_github("andrewsali/shiny")
```

**Comment by andrewsali** [comment] 2018-04-18 20:02
The fix has now been incorporated into rstudio/shiny in github.

**Closed by andrewsali** 2018-04-18 20:02 UTC

**Comment by dylancis** [comment] 2018-04-19 06:11
We just need to update shiny to have it fixed or is there any code change required here ? Thanks.

**Comment by andrewsali** [comment] 2018-04-19 06:29
No code change required, just install shiny from github via:

```devtools::install_github("rstudio/shiny")```

**Comment by lizigarland96** [comment] 2020-04-28 14:58
Is this version of shiny updated in CRAN?

**Comment by daattali** [comment] 2020-04-28 15:45
The current cran version is from 3 months ago. If something is failing for you, please test using this version: `devtools::install_github('daattali/shinycssloaders')`

**Comment by lizigarland96** [comment] 2020-04-28 16:08
I am unable to test with that version due to "port 443: Bad Access"

**Comment by daattali** [comment] 2020-04-28 16:13
That doesnt look like a shinycssloaders issue. Try 
- restarting rstudio
- restarting your computer
- uninstall+reinstall shiny
- uninstall+reinstall shinycssloaders

Any combination of the above, preferably all of them. But that's definitely not an issue of this package

**Comment by lizigarland96** [comment] 2020-04-28 16:33
I am unable to install version: devtools::install_github('daattali/shinycssloaders') due to a corporate wall. But I am still experiencing spinning issues with tableOutput, using Shiny version 1.4.0.2 and shinycssloaders 0.3 under R version 3.6.0

**Comment by daattali** [comment] 2020-04-28 16:39
If you believe there's a bug in the package, please send a minimal
reproducible code sample

**Comment by aavanesy** [comment] 2020-05-12 07:08
Hi,
I have the same issue. Reinstalled shiny and installed the package from github.
Spinner keeps running if the rendered object is unchanged.

**Comment by daattali** [comment] 2020-05-12 07:10
If you believe there's a bug, please include a small reproducible sample code so I can see it and troubleshoot.

**Comment by taustring** [comment] 2020-11-10 03:12
@daattali I have a similar issue where I have included an actionButton to download data from the web to cache locally and use when offline but withSpinner active on the button, it spins from loading the app without any user input when it should only be active while the data pull is processing, and also prevents clicking the button.

I reproduced the issue with the sample app, I just turned the button in to a reset button to restore the original value of the slider.  The function of the button isn't the same as my application, but it is behaving the same.  The button works as it should if the spinner is removed, but the button isn't clickable with the spinner active since it is constantly "refreshing."

```
library(shiny)
library(shinyjs)
library(shinycssloaders)

ui <- fluidPage(

    shinyjs::useShinyjs(),

    sidebarLayout(
        sidebarPanel(
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30),
            
            actionButton(inputId = "refresh", label = "Refresh Cache") 
                %>% withSpinner(type = 4, color = "blue", size = 1, hide.ui = FALSE)
            ),

        mainPanel(
           plotOutput("distPlot")
        )
    )
)

server <- function(input, output) {

    observeEvent(input$refresh, {
        shinyjs::reset("bins")
    })
    
    output$distPlot <- renderPlot({
        x    <- faithful[, 2]
        bins <- seq(min(x), max(x), length.out = input$bins + 1)
        hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment] 2020-11-10 03:16
shinycssloaders works for **outputs** specifically. Action buttons are inputs, not outputs. This package does not work with buttons

**Comment by taustring** [comment] 2020-11-10 03:26
@daattali thanks for the clarification, modified my google search and realized that it's an easy solution, just not as pretty as a spinner.

```
observeEvent(input$refresh, {
        showModal(modalDialog("Downloading Data..."))
        #data pulls 
        removeModal()
})

**Comment by daattali** [comment] 2020-11-10 05:13
Yeah, you can use `shinyalert` if you want it to look a little bit prettier, but anything other than `shinycssloaders` wil lrequire you to manually decide when to show/hide
